version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:80"
    environment:
      NODE_ENV: production
